---
title: "DSC520 Week5 - 5.2 Exercise"
author: "Maxim Bilenkin"
date: "2025-01-07"
output: pdf_document
---

```{r setup, echo=TRUE, eval=TRUE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# Setting CRAN mirror.
options(repos = c(CRAN = "https://cran.rstudio.com/"))

# Installing necessary packages if not already installed
necessary_packages <- c("dplyr", "readxl", "purrr")
new_packages <- necessary_packages[!(necessary_packages %in% 
                                         installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)

# Loading necessary packages
library(dplyr)
library(readxl)
library(purrr)


```

```{r dplyr-operations, echo=TRUE}

# a. Using the dplyr package, use the 6 different operations to 
#    analyze/transform the data - GroupBy, Summarize, Mutate, Filter, Select, 
#    and Arrange – Remember this isn’t just modifying data, you are learning 
#    about your data also – so play around and start to understand your dataset 
#    in more detail.

# Loading the Housing dataset file.
housing_data_file <- read_excel("C:/Users/maxim/Downloads/week-6-housing.xlsx")

# Displaying column names to identify the correct ones
print(head(colnames(housing_data_file), 5))

# Temporarily set output width to prevent truncation
options(width = 80)

# Displaying the first 5 rows to understand data structure
print(head(housing_data_file, 5))

# Check and print column types with controlled width and list length
print(str(housing_data_file, width = 70, list.len = 5))

# Ensuring 'Sale Price' is numeric and handling non-numeric characters
housing_data_file <- housing_data_file %>%
  mutate(`Sale Price` = as.numeric(gsub("[^0-9.]", "", 
                                        as.character(`Sale Price`))))

# Display the first 5 rows to confirm changes
print(head(housing_data_file, 5))

# Reset the output width to default
options(width = 80)

# Grouping data by 'sitetype'.
grouped_by_site_type <- housing_data_file %>% group_by(sitetype)

# Summarizing average housing price by sitetype.
summarized_data <- grouped_by_site_type %>%
  summarize(average_price = mean(`Sale Price`, na.rm = TRUE))

# Calculating and creating a new column for price per square foot.
mutated_data <- housing_data_file %>% 
  mutate(price_per_sqft = `Sale Price` / square_feet_total_living)

# Filtering houses with more than 2 bedrooms.
houses_with_more_than_2_bedrooms <- housing_data_file %>%
  filter(bedrooms > 2)

# Selecting specific columns.
specific_columns <- housing_data_file %>%
  select(`Sale Price`, square_feet_total_living, bedrooms)

# Sorting the data by Sale Price in descending order.
sorted_data <- housing_data_file %>%
  arrange(desc(`Sale Price`))

# Completed data set after transformation.
completed_data_set <- housing_data_file %>%
  filter(bedrooms > 2) %>%
  mutate(price_per_square_foot = `Sale Price` / square_feet_total_living) %>%
  select(sitetype, `Sale Price`, square_feet_total_living, 
         price_per_square_foot, bedrooms) %>%
  arrange(desc(price_per_square_foot))

# Displaying the first 5 rows of the completed data set sample.
print(head(completed_data_set, 5))




```

```{r purrr-operations, echo=TRUE}


# b. Using the purrr package – perform 2 functions on your dataset. You could 
#    use zip_n, keep, discard, compact, etc.

# Making data frames to have the same length otherwise system throws an error.
min_length <- min(nrow(mutated_data), nrow(houses_with_more_than_2_bedrooms),
                  nrow(sorted_data))
mutated_data <- mutated_data[1:min_length, ]
houses_with_more_than_2_bedrooms <- 
    houses_with_more_than_2_bedrooms[1:min_length, ]
sorted_data <- sorted_data[1:min_length, ]

# Ensuring all data frames have the same columns otherwise system throws error.
common_cols <- Reduce(intersect, list(names(mutated_data), 
                                      names(houses_with_more_than_2_bedrooms), 
                                      names(sorted_data)))
mutated_data <- mutated_data[, common_cols]
houses_with_more_than_2_bedrooms <- 
    houses_with_more_than_2_bedrooms[, common_cols]
sorted_data <- sorted_data[, common_cols]

# Converting data frames to lists of columns.
mutated_list <- as.list(mutated_data)
houses_2_plus_bedrooms_list <- as.list(houses_with_more_than_2_bedrooms)
sorted_data_list <- as.list(sorted_data)

# Using 'purrr' package and 'pmap' method to combine three lists. The zip_n()
# method not found in purrr package. Thus, using similar pmap() instead.
combined_multiple_columns <- pmap(list(mutated_list, 
                                       houses_2_plus_bedrooms_list, 
                                       sorted_data_list), 
                                  function(x, y, z) list(x, y, z))

# Converting combined multiple columns of lists to a data frame for better readability. 
combined_df <- data.frame( 
    Sale_Date = sapply(combined_multiple_columns[[1]], function(x) x[[1]]), 
    Sale_Price = sapply(combined_multiple_columns[[2]], function(x) x[[1]]), 
    Sale_Reason = sapply(combined_multiple_columns[[3]], function(x) x[[1]]), 
    Sale_Instrument = sapply(combined_multiple_columns[[4]], function(x) x[[1]]), 
    Sale_Warning = sapply(combined_multiple_columns[[5]], function(x) x[[1]]) )

# Using keep() method to filter and keep only numeric columns from combined_df. 
combined_numeric_columns <- keep(combined_df, is.numeric)

# Displaying summarized data frame.
print(head(combined_numeric_columns,5))

```


```{r cbind/rbind-functions, echo=TRUE}

# c. Use the cbind() and rbind() function on your dataset.

# Creating vector with 'Sale Price'.
sale_price <- housing_data_file$'Sale Price'

# Creating vector with complete address using the following columns.
address <- housing_data_file %>% select(addr_full, zip5, ctyname, postalctyn)

# Using cbin() method combining both vectors.
combined_two_vectors <- cbind(sale_price, address)

# Printing the first 5 rows of the combined two vectors.
print(head(combined_two_vectors, 5))

# Creating two subsets from dataset file.
subset1 <- housing_data_file[1:5, c("Sale Price", "addr_full", "zip5", 
                                    "ctyname", "postalctyn")]
subset2 <- housing_data_file[6:10, c("Sale Price", "addr_full", "zip5", 
                                     "ctyname", "postalctyn")]

# Combining both subsets with rows using rbind() method.
combined_rows_data <- rbind(subset1, subset2)

# Printing the file with combined two subsets with rows.
print(combined_rows_data)

```

```{r split/concatenate-operations, echo=TRUE}

# d. Split a string, then concatenate the results back together.

# Taking 'addr_full' column and making sure it is a character.
housing_data_file <- housing_data_file %>% 
    mutate(addr_full = as.character(addr_full))

# Splitting the addr_full column into words.
splitted_addr_full <- strsplit(housing_data_file$addr_full, " ")

# Displaying the first 5 splitted addresses to verify.
print(head(splitted_addr_full, 5))

# Concatenating the splitted words back into one sentence using hyphen "-".
concatenated_address <- sapply(splitted_addr_full, function(x) 
    paste(x, collapse ="-"))

# Creating new column to add concatenated address line in the data file.
housing_data_file <- housing_data_file %>% 
    mutate(concatenated_address = concatenated_address)

# Printing first 5 rows of the new crated alternate housing data file.
print(housing_data_file[1:5, c("addr_full", "concatenated_address")])

```